### PR TITLE
Add page archiver

### PR DESCRIPTION
**Pull request by ondenman**
Adds scraped page archive gem.

### CODE REVIEW

**Review by tmtmtmtm — CHANGES_REQUESTED** [review]
screen shot 2016-09-28 at 09 08 27

**Comment by ondenman** [comment]
Updated repo description

**Comment by ondenman** [comment]
⚠️ Morph environment needs to be configured

**Comment by tmtmtmtm** [comment]
👍  — now archived at https://github.com/everypolitician-scrapers/curacao-parliament/tree/scraped-pages-archive

**Pull request merged**
